EDRPOU validation
Vitaliy-1/openHealth pull request #82
Opened 2024-11-01 14:40 UTC by lemadior

ISSUE: https://github.com/Vitaliy-1/openHealth/issues/81
Fix validation about wrong specified EDRPOU before signing data by KEP.

2024-11-01 14:42 UTC, lemadior commented on package-lock.json
I don't know is need to commit it but decided to.

2024-11-01 14:53 UTC, Vitaliy-1 commented on package-lock.json
Це ви оновили npm dependecies. Його комітить треба лише якщо ви додавали щось нове, накриклад, нову js бібліотеку. Update буде робити або @biben1989 або я - там треба обовʼязкове протестувати, чи все сумісно. Хай вже буде в цьому PR. Те саме стосовно composer залежностей.

2024-11-01 14:54 UTC, lemadior commented on package-lock.json
Got it.

2024-11-03 09:45 UTC, Vitaliy-1 requested changes
Дякую! Залишив коментарі. Треба буде внести виправлення та зробити rebase. В понеділок обговоримо.

2024-11-03 09:45 UTC, Vitaliy-1 commented on app/Classes/Cipher/Api/CipherApi.php
> +                'message' => __('validation.custom.edrpou_differ'),
Є ще якісь дані, які ми можемо на даному етапі перевірити, наприклад, ПІБ?

2024-11-03 09:49 UTC, lemadior commented
Ок

нд, 3 лист. 2024, 10:45 користувач Vitaliy ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> Дякую! Залишив коментарі. Треба буде внести виправлення та зробити rebase.
> В понеділок обговоримо.
> ------------------------------
>
> In app/Classes/Cipher/Api/CipherApi.php
> <https://github.com/Vitaliy-1/openHealth/pull/82#discussion_r1826850064>:
>
> > +
> +    /**
> +     * Check if some important data received from the forms are have the same value as in the DS FileContainer
> +     *
> +     * @param string $dataSignature Data from legal_entity_form
> +     *
> +     * @return void
> +     */
> +    public function verifyWithFileContainer(string $dataSignature): void
> +    {
> +        // Get all data stored into the key
> +        $response = $this->getFileContainerInfo($this->password);
> +
> +        $personalData = $response['signature']['certificateInfo']['extensionsCertificateInfo']['value']['personalData'] ?? [];
> +        // Get value of 'edrpou' field for key's owner {string|null}
> +        $inKeyEdrpou = $personalData['value']['edrpou']['value'] ?? '';
>
> https://laravel.com/docs/11.x/helpers#method-array-get
>
> $inKeyEdrpou = Arr::get($array, 'signature.certificateInfo.extensionsCertificateInfo.value.personalData.value.edrpou.value', '');
>
> ------------------------------
>
> In app/Rules/UniqueEdrpou.php
> <https://github.com/Vitaliy-1/openHealth/pull/82#discussion_r1826860344>:
>
> > @@ -12,8 +12,9 @@ class UniqueEdrpou implements ValidationRule
>
>      public function __construct(?int $legalEntityId = null)
>      {
> +        $auth = auth();
>
> Для хелперів це не обовʼязково, це не буде впливати на швидкість виконання
> коду. Цей хелпер звертається до обʼєкту, який привʼязаний до контейнера
> Laravel
> https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/helpers.php#L168.
> Я більш детально поясню. Документація про контейнер і привʼязування
> (binding) сутностей, якщо цікаво https://laravel.com/docs/11.x/container
> ------------------------------
>
> In app/Classes/Cipher/Api/CipherApi.php
> <https://github.com/Vitaliy-1/openHealth/pull/82#discussion_r1826931704>:
>
> > +     */
> +    public function verifyWithFileContainer(string $dataSignature): void
> +    {
> +        // Get all data stored into the key
> +        $response = $this->getFileContainerInfo($this->password);
> +
> +        $personalData = $response['signature']['certificateInfo']['extensionsCertificateInfo']['value']['personalData'] ?? [];
> +        // Get value of 'edrpou' field for key's owner {string|null}
> +        $inKeyEdrpou = $personalData['value']['edrpou']['value'] ?? '';
> +
> +        // Get from data as object. Here 'edrpou' just object's field.
> +        $legalEntityFormData = json_decode($dataSignature);
> +
> +        if ($inKeyEdrpou !== $legalEntityFormData->edrpou) {
> +            $error = ErrorHandler::handleError([
> +                'message' => __('validation.custom.edrpou_differ'),
>
> Є ще якісь дані, які ми можемо на даному етапі перевірити, наприклад, ПІБ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vitaliy-1/openHealth/pull/82#pullrequestreview-2411742177>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYWUJIGUC76FVKSSHMSSEM3Z6XPC3AVCNFSM6AAAAABRAMJSKWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJRG42DEMJXG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-03 09:50 UTC, lemadior commented on app/Classes/Cipher/Api/CipherApi.php
> +        $inKeyEdrpou = $personalData['value']['edrpou']['value'] ?? '';
Ok

2024-11-03 09:53 UTC, lemadior commented on app/Classes/Cipher/Api/CipherApi.php
> +                'message' => __('validation.custom.edrpou_differ'),
Так, ми можемо перевірити П.І.Б, але я поки не до кінця розумую тут бізнес-логіку, тому краще уточнити у Владислава

2024-11-04 12:08 UTC, closed without merging