#83 Add main helper classes
Vitaliy-1/openHealth pull request #87
Opened 2024-11-06 14:56 UTC by lemadior

Add new helper dictionary(). But remain all the existent stuff to works with dictionaries. Change two forms (LegalEntities & Division) to show how to use new helper. All the old code was remain but commented.

2024-11-06 22:32 UTC, Vitaliy-1 requested changes
Дякую! Залишив пару коментарів стосовно патерну коду.

2024-11-06 22:32 UTC, Vitaliy-1 commented on app/Providers/AppServiceProvider.php
> +        $this->app->singleton(DictionaryService::class, function ($app) {
```php
$this->app->singleton(DictionaryService::class, fn ($app) => new DictionaryService)

2024-11-06 22:32 UTC, Vitaliy-1 commented on app/Providers/AppServiceProvider.php
> +        if (empty(Division::$types)) {
По логіці ми маємо передати при завантаженні дані, які потрібні для конфігурації, наприклад, винести в config шлях до API ендпоінта для Dictionaries. І якщо вони не в кеші то завантажити.

2024-11-06 22:32 UTC, Vitaliy-1 commented on app/Services/DictionaryService.php
> +    // public function searchByKeys(array $keys, bool $isArray = false): array
Закоментовані рядки мають бути прибрані?

2024-11-06 22:32 UTC, Vitaliy-1 commented on app/Providers/AppServiceProvider.php
> +        $this->app->singleton(DictionaryService::class, function ($app) {
А як ви дивитесь на створення окремого [сервіс провайдера](https://laravel.com/docs/11.x/providers)? І зробити його defered? https://laravel.com/docs/11.x/providers#deferred-providers. Я не думаю, що довідники нам потрібні при кожному запиті.

2024-11-06 22:32 UTC, Vitaliy-1 commented on app/Providers/AppServiceProvider.php
> +        if (empty(Division::$types)) {
Скажімо, тут ми викликаємо `Dictionary::setDictionaries()`, в цей метод ми переносимо перетворення із `JsonHelper`. По задуму патерна, вся логіка має бути інкапсульована в Service Provider.

2024-11-06 22:37 UTC, lemadior commented on app/Providers/AppServiceProvider.php
> +        $this->app->singleton(DictionaryService::class, function ($app) {
Ок. Я гляну.

2024-11-06 22:41 UTC, lemadior commented on app/Services/DictionaryService.php
> +    // public function searchByKeys(array $keys, bool $isArray = false): array
Так. Звичайно.
Це я залишив для демонстрації загальних можливостей, оскільки даний клас ще на етапі створення. Можливо те, що там закоментовано - згодиться для чогось іншого. Там код повністю робочий.

2024-11-13 16:01 UTC, lemadior commented
В класі DivisonIndex я навмисне залишив коменти, щоб залишався "старий" код і можна було порівняти з тим, як працює хелпер.

2024-11-13 16:24 UTC, Vitaliy-1 requested changes
Дякую! Два швидких коментаря по структурі класів.

2024-11-13 16:24 UTC, Vitaliy-1 commented on app/Helpers/JsonHelper.php
Цей клас містить логіку роботи dictionaries? Його вміст має бути в DictionaryService

2024-11-13 16:24 UTC, Vitaliy-1 commented on app/Providers/DictionaryServiceProvider.php
> +        $this->app->singleton(DictionaryService::class, fn ($app) => new DictionaryService());
Тут ми маємо пропустити URL до Dictionaries в якості конфіг параметра
```php
new DictionaryService($app['config']['dictionary']))
```

2024-11-13 16:24 UTC, Vitaliy-1 commented on config/app.php
> +        App\Providers\DictionaryServiceProvider::class
Мабуть, пропущений новий рядок.

2024-11-13 16:41 UTC, lemadior commented on app/Helpers/JsonHelper.php
Я звідти тільки використовую функцію "забору" даних. Цей клас має метод, який забирає дані по API й зберігає їх у кеш. Потім віддає з кешу. Інший код я не використовую. Його теж треба розмістити в DictionaryService?

2024-11-13 16:44 UTC, lemadior commented on app/Providers/DictionaryServiceProvider.php
> +        $this->app->singleton(DictionaryService::class, fn ($app) => new DictionaryService());
Ок. Та що має бути в конфігу в параметрі 'dictionary'? Там же при створенні new DictionaryService() все, що віддає API поміщається в цей клас. Тобто весь dictionary...

2024-11-13 18:36 UTC, Vitaliy-1 commented on app/Helpers/JsonHelper.php
Тільки те, що стосується лише dictionary

2024-11-19 09:57 UTC, Vitaliy-1 requested changes
Дякую! Залишив пару коментарів

2024-11-19 09:57 UTC, Vitaliy-1 commented on app/Helpers/JsonHelper.php
>              $response = file_get_contents(self::DICTIONARIES_API_URL);
Частина логіки по словникам із цього класу має бути перенесена в DictionaryService.

2024-11-19 09:57 UTC, Vitaliy-1 commented on app/Helpers/JsonHelper.php
> +    public static function getDictionaries() {}
Це, мабуть, лишнє.

2024-11-19 09:57 UTC, Vitaliy-1 commented on app/Livewire/Division/DivisionIndex.php
> +        // $this->dictionaries = JsonHelper::searchValue('DICTIONARIES_PATH', [
Цей блок треба прибрати?

2024-11-19 09:57 UTC, Vitaliy-1 commented on app/Livewire/Division/DivisionIndex.php
> +    //    public function openModal()
Цей теж

2024-11-19 10:03 UTC, lemadior commented on app/Helpers/JsonHelper.php
>              $response = file_get_contents(self::DICTIONARIES_API_URL);
Яка саме? Те, що відноситься до забору даних з API-ресурсу там є. Інший функціонал - продубльований власними методами.

2024-11-19 10:13 UTC, lemadior commented on app/Livewire/Division/DivisionIndex.php
> +        // $this->dictionaries = JsonHelper::searchValue('DICTIONARIES_PATH', [
Я його залишав як приклад того, як було зроблено раніше. Якщо @biben1989 не проти того, як зроблено по-новому, то так - це можна прибрати.

2024-11-19 11:33 UTC, Vitaliy-1 commented on app/Livewire/Division/DivisionIndex.php
> +        // $this->dictionaries = JsonHelper::searchValue('DICTIONARIES_PATH', [
Можна видаляти

2024-11-19 12:12 UTC, lemadior commented on app/Helpers/JsonHelper.php
>              $response = file_get_contents(self::DICTIONARIES_API_URL);
Наскільки я розумію - так. Він використовується лише для забору й віддачі даних по словниках.

2024-11-19 12:33 UTC, merged